apiVersion: apps/v1
kind: Deployment
metadata:
  name: puppeteer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: puppeteer
  template:
    metadata:
      labels:
        app: puppeteer
    spec:
      containers:
        - name: puppeteer
          image: urlbox-puppeteer-kubernetes-demo:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000